# Generated by Django 3.2.13 on 2024-03-12 13:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('about', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About')),
                ('mision', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mission')),
                ('vision', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Vision')),
                ('image_google', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('url_google', models.URLField(blank=True, null=True, verbose_name='URL Google Business')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('title', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Banner title')),
                ('title2', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Banner title2')),
                ('subtitle', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Banner subtitle')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Description')),
                ('insurance', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Insurance')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True, verbose_name='Location')),
                ('phone1', models.CharField(blank=True, max_length=60, null=True, verbose_name='Phone 2')),
                ('phone2', models.CharField(blank=True, max_length=60, null=True, verbose_name='Phone 1')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('title1', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title 1')),
                ('number1', models.IntegerField(blank=True, null=True, verbose_name='Number 1')),
                ('symbol1', models.CharField(blank=True, max_length=300, null=True, verbose_name='Symbol 1')),
                ('title2', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title 2')),
                ('number2', models.IntegerField(blank=True, null=True, verbose_name='Number 2')),
                ('symbol2', models.CharField(blank=True, max_length=300, null=True, verbose_name='Symbol 2')),
                ('title3', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title 3')),
                ('number3', models.IntegerField(blank=True, null=True, verbose_name='Number 3')),
                ('symbol3', models.CharField(blank=True, max_length=300, null=True, verbose_name='Symbol 3')),
                ('title4', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title 4')),
                ('number4', models.IntegerField(blank=True, null=True, verbose_name='Number 4')),
                ('symbol4', models.CharField(blank=True, max_length=300, null=True, verbose_name='Symbol 4')),
            ],
            options={
                'verbose_name': 'Counter',
                'verbose_name_plural': 'Counters',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Faq',
                'verbose_name_plural': 'Faqs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='partner/')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Privacy',
                'verbose_name_plural': 'Privacies',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='Icon/')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Service Name')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_finish', models.TextField(blank=True, null=True, verbose_name='Finish Description')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('title1', models.CharField(blank=True, max_length=300, null=True, verbose_name='Skill title 1')),
                ('description1', models.TextField(blank=True, null=True, verbose_name='Description 1')),
                ('title2', models.CharField(blank=True, max_length=300, null=True, verbose_name='Skill title 2')),
                ('description2', models.TextField(blank=True, null=True, verbose_name='Description 2')),
                ('title3', models.CharField(blank=True, max_length=300, null=True, verbose_name='Skill title 3')),
                ('description3', models.TextField(blank=True, null=True, verbose_name='Description 3')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('01', 'Facebook'), ('02', 'Twitter'), ('03', 'Instagram'), ('04', 'TikTok'), ('05', 'YouTube'), ('06', 'LinkedIn')], max_length=2, verbose_name='Name')),
                ('url', models.URLField(verbose_name='URL')),
                ('icon_class', models.CharField(max_length=150, verbose_name='Icon class')),
                ('icon_class_footer', models.CharField(max_length=150, verbose_name='Icon class footer')),
            ],
            options={
                'verbose_name': 'SocialMedia',
                'verbose_name_plural': 'SocialMedias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonial/')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Name')),
                ('location', models.CharField(blank=True, max_length=300, null=True, verbose_name='Location')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, choices=[('01', 'Roofing'), ('02', 'Flat Roofing'), ('04', 'Siding'), ('05', 'Gutter'), ('06', 'Window'), ('07', 'Carpentry'), ('08', 'Remodeling')], max_length=2, null=True, verbose_name='Category')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Image title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='work_image/')),
            ],
            options={
                'verbose_name': 'WorkImage',
                'verbose_name_plural': 'WorkImages',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subservice/')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Subservice Name')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_subservice', to='app_core.service')),
            ],
            options={
                'verbose_name': 'SubService',
                'verbose_name_plural': 'SubServices',
                'ordering': ['id'],
            },
        ),
    ]
